### PR TITLE
Update Display methods and support

### PR DESCRIPTION
**Pull request by matrix224**
* Updated Display so it only uses one method for drawing and will subsequently only draw the screen once per update instead of two
* Updated Display's draw method to check for adapter having a pointer set as opposed to what screen is set in config whenever needing to reference it
    * I did this since it seemed like a few different screens could use the same adapter and were ultimately doing the same things, so instead of a bunch of if-else's for them or one long if with a bunch of ||'s, it felt more clean to just check if the adapter is actually initialized and use it if so
    * I think this also fixed a potential bug in the startScreen() method if using an SSD1305 since it was trying to set up the SSD1306 adapter at the end regardless?
* Added support for "IDEASPARK_SSD1306" display

### CODE REVIEW

**Comment by dj1ch** [comment]
> Not sure what's going on with the restyling, but it doesn't seem to want to apply the patches for me:
> 
> ```
> error: patch failed: minigotchi/display.cpp:9
> error: minigotchi/display.cpp: patch does not apply
> error: patch failed: minigotchi/display.h:35
> error: minigotchi/display.h: patch does not apply
> ```

looks like you'll need to run it on the same branch you opened the PR on, try running the latest patch from `m224_ideaspark_display`

**Comment by matrix224** [comment]
> looks like you'll need to run it on the same branch you opened the PR on, try running the latest patch from `m224_ideaspark_display`

Yeah I was. I tried switching to another and then back and trying again just to be extra sure, but same deal:
upload_c3af118c878e3f11_1718233510

**Comment by dj1ch** [comment]
> > looks like you'll need to run it on the same branch you opened the PR on, try running the latest patch from `m224_ideaspark_display`
> 
> Yeah I was. I tried switching to another and then back and trying again just to be extra sure, but same deal: upload_c3af118c878e3f11_1718233510

restyle is kinda weird like that sometimes. add a commit (like a random comment or something) in a file, this should make it recheck the code.

**Comment by dj1ch** [comment]
i should also mention we could also close #133 after we merge this pr

**Review by dj1ch — APPROVED** [review]
lgtm👍

**Comment by matrix224** [comment]
Alright after several fights with restyle I figured out what it seemed to want: a comment in display.h to be updated
It seems I've appeased the beast now

**Review by dj1ch — APPROVED** [review]

**Pull request merged**
